const people = [
    ["Horse-people", "Tiefling", "Crane Wilder", "Storm Eladrin", "Aboleth"],
    ["Kobold", "Vine-people", "Stone Giant", "Staff Guardian", "Darkness Giant"],
    ["Human", "Owl Were", "Human Secrecy/Fire Axial", "Crown Guardian", "Darkness Dragon"],
    ["Orc", "Mammoth/Goose L'na", "Sword Guardian", "Staff Guardian", "Gold Dragon"],
    ["Elf", "Owl Were", "Orc Secrecy/Earth Axial", "Sea Eladrin", "Darkness Dragon"],
    ["Weasel-people", "Centaur", "Ogre Air Genasi", "Crown Guardian", "Darkness Giant"],
    ["Locust-people", "Ogre", "Forest Giant", "Sand Giant", "Sea Giant"],
    ["Human", "Human Storm Genasi", "Centaur Plant Genasi", "Aasimar Luck/Winter Axial", "Silver Dragon"],
    ["Condor-people", "Bear/Alligator L'na", "Alligator Wilder", "Cloud Giant", "Storm Giant"],
    ["Human", "Tiefling", "Sword Guardian", "Stone Dragon", "Silver Dragon"],
    ["Bugbear", "Rat/Owl L'na", "Shield Guardian", "Staff Guardian", "Aboleth"],
    ["Deer-people", "Flower-people", "Forest Giant", "Forest Eladrin", "Sea Giant"],
    ["Human", "Cylinder Droid", "Ogre Plant Genasi", "Tiefling Secrecy/Darkness Axial", "Sea Giant"],
    ["Dwarf", "Insectoid Droid", "Sahuagin Luck/Force Axial", "Sand Giant", "Sea Giant"],
    ["Bugbear", "Aasimar", "Sea Fey", "Ogre Chaos/Force Axial", "Storm Dragon"],
    ["Gnoll", "Shark Were", "Stone Giant", "Bronze Dragon", "Silver Dragon"],
    ["Human", "Bear/Locust L'na", "Human Secrecy/Earth Axial", "Copper Dragon", "Aboleth"],
    ["Ant-people", "Centaur", "Winter Fey", "Fire Giant", "Storm Giant"],
    ["Human", "Ogre", "Kobold Luck/Earth Axial", "Aasimar Healing/Force Axial", "Darkness Dragon"],
    ["Ox-people", "Chuul", "Forest Giant", "Brass Dragon", "Darkness Giant"],
    ["Goblin", "Centaur", "Boar Wilder", "Fire Giant", "Sea Giant"],
    ["Termite-people", "Troll", "Human Might/Earth Axial", "Brass Dragon", "Aboleth"],
    ["Kobold", "Chuul", "Forest Giant", "Aasimar Healing/Plant Axial", "Darkness Giant"],
    ["Parrot-people", "Sphere Droid", "Tiefling Fire Genasi", "Ogre Secrecy/Air Axial", "Silver Dragon"],
    ["Rat-people", "Grass-people", "Lizardfolk Justice/Air Axial", "Sand Giant", "Storm Dragon"],
    ["Elf", "Tree-people", "Halfling Secrecy/Earth Axial", "Forest Dragon", "Sea Dragon"],
    ["Rat-people", "Centaur", "Stone Giant", "Brass Dragon", "Silver Dragon"],
    ["Kobold", "Ogre", "Ogre Earth Genasi", "Crown Guardian", "Darkness Giant"],
    ["Gnoll", "Aasimar", "Human Luck/Darkness Axial", "Fire Giant", "Darkness Dragon"],
    ["Drow", "Bear/Gull L'na", "Desert Fey", "Aasimar Secrecy/Force Axial", "Sea Giant"],
    ["Falcon-people", "Insectoid Droid", "Sword Guardian", "Sand Giant", "Darkness Giant"],
    ["Human", "Flower-people", "Human Transmutation/Fire Axial", "Sand Giant", "Storm Dragon"],
]

module.exports = people